credentials:
  usernames:
    # Username: jsmith
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: '$2b$12$Eu7rEUthAppLaeiyHRkZE.rLwR3N65ZWHHfz.A1RW3DgZv8IX3Eh6' # Replace with actual hashed password
    # Username: rdoe
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: '$2b$12$NNY.ZtG5H372DfvIQhxyee1mmao/08gwq/9hrJWC/bnaOYqgGAhdO'  # Replace with actual hashed password
cookie:
  expiry_days: 30
  key: 'some_random_signature_key' # Choose a random secret key
  name: 'some_cookie_name'
preauthorized:
  emails:
  - melsby@example.com # Optional: For pre-authorizing users if using social login later